### ISSUE TITLE
Что делает отрывает видео просто?

### ISSUE THREAD

**Issue by bitcoin5000** [wipedlifepotato/VnukuElkina#1]
Это я как понял ловит донат и открывает видео просто? но так это вроде встроенными средствами донатпея можно сделать, весь смысл проверить вручную чтобы херню какуюто не прислали и чтобы была очередь. Надо чтобы собирала видео и добавляла в таблицу csv файл с сумой доната и продолжительностью видео и выводила стоимость за минуту скока заплатили коэффициент чтобы по нему можно отсортировать 
типо
https://www.youtube.com/watch?v=feJsIaj579Q | Хроника событий нападения на Алексея | 5 | 50 | 10
-- | -- | -- | -- | --

**Comment by wipedlifepotato** [comment]
Именно cvs?

вт, 12 мая 2020 г., 4:09 bitcoin5000 <notifications@github.com>:

**Comment by wipedlifepotato** [comment]
Мб sqlite? CSV в реальном времени... Есть такое на Винду?

**Comment by wipedlifepotato** [comment]
Смотри, тут даже сумма переводится в то сколько смотреть минут, открывает браузер за тебя, ссылку ютуба(херню я там показал, все кроме ютуба не открывает). Но сейчас чонить сделаю для парсинга инфо о самом видео. C дальнейшей записью в файл, там уже его чтение в реальном времени, далее копируешь чо надо.

**Comment by wipedlifepotato** [comment]
https://pypi.python.org/pypi/pafy/0.3.42

**Comment by wipedlifepotato** [comment]
user@I2Pd:~/VnukuElcina$ python3 main_csv.py 
wait new videos
https://www.youtube.com/watch?v=iQI0zJd_cK4
write to last id: 10475505
Титл Title:b"Nightcore - Don't Stop\n" | время Duration:b'2:56\n' | Оплачено 1000.00 | минут проплачено 100 
UPD:
write to last id: 10475505
Титл Title:b"Nightcore - Don't Stop\n" | время Duration:b'2:56\n' | Оплачено 1000.00 | минут проплачено 100 | адрес(url) https://youtube.com/watch?v=iQI0zJd_cK4

**Comment by wipedlifepotato** [comment]
#TODO: собрать массив из этих видосов. и разобраться как лучше сортировать, и удалять то что посмотренно. 
https://github.com/wipedlifepotato/VnukuElkina/commit/df1e018c83d93f0c5a779e0db61565752ae526d9

**Comment by wipedlifepotato** [comment]
@bitcoin5000 ты в ручную будешь отсортировывать? и удалять старое из файла? я сделаю, что бы в него записывалось то, что ещё не добавленно, ладно? ты уже редактором увидешь типа файл был обновлен, тыкнешь обновить, и увидешь новые записи, старые руками. Или лучше массив сделать, и в ряд, где заплатили больше, переписав файл?

То есть, люди донятат, выстраивается там где донат был больше. 
Файл обновляется, переписывается полностью. Но как потом удалять старое, если у нас нет GUI или ещё чего... Короче если ты в ручную это будешь делать, прямо сейчас могу доделать запись в файл, и можешь уже пользоваться. Если не в ручную, то надо дописать гуи. Сейчас покурю, покушаю там, сделаю пока что что бы в файлик писалось. Потом попробую гайд написать как запустить этот говнокод на винде, если не разберешься, если разберешься, то воще збс

**Comment by wipedlifepotato** [comment]
Если надо будет, что бы удалять через CLI/GUI уже посмотренное, то напиши, да и если не надо, тоже пжл.

**Comment by wipedlifepotato** [comment]
https://github.com/wipedlifepotato/VnukuElkina/blob/master/main_csv.py

**Comment by wipedlifepotato** [comment]
@bitcoin5000 я добавил по csv, пишет в файл последнии, и пофиксил с последними транзакциями(донатами). 
Но тут минут, требуется файл youtube-dl(.exe) 
Все остальное работает, и перепроверил несколько раз. 
Оставил main старый. Смотрит донаты, ищет в комментарии видео на ютуб. Открывает его. Ставит на паузу (в конфиге ставится стоимость по минуте) %сумма доната%/config.price * 60 там секунд.
А в main_csv новые смотрит, пишет в файл csv.
Сейчас выхлоп покажу примерный: (Минус требуется в ручную удалять то что уже посмотрено(снова он добавлять не будет))
Ну и опять же нужен youtube-dl/splinter/geckodriver 
Ну и питон, крч если такое катит, отпиши, я закрою тогда иссуй. Если нет напиши.
Если нужна документация, то этот иссуй всеровно закрой и создай новый, спасибо.

Вот пример выхлопа: (для main_csv)
```
user@I2Pd:~/VnukuElcina$ cat Videos.csv 
title|url|payed|duration|minutes_payed
"b""Nightcore - Don't Stop\n"""|https://youtube.com/watch?v=iQI0zJd_cK4|1000.00|b'2:56\n'|100.0
b'Nightcore - Ievan Polkka (VSNS Remix)\n'|https://youtube.com/watch?v=QwdbFNGCkLw|40.00|b'3:51\n'|4.0
b''|https://youtube.com/watch?v=zS-VY7BbTls|1110.00|b''|111.0
"b""Nightcore - Don't Stop\n"""|https://youtube.com/watch?v=iQI0zJd_cK4|1111.00|b'2:56\n'|111.1
"b""Nightcore - Don't Stop\n"""|https://youtube.com/watch?v=iQI0zJd_cK4|100.00|b'2:56\n'|10.0
b'Nightcore - Ievan Polkka (VSNS Remix)\n'|https://youtube.com/watch?v=QwdbFNGCkLw|100.00|b'3:51\n'|10.0
b''|https://youtube.com/watch?v=zS-VY7BbTls|100500.00|b''|10050.0
"b""Nightcore - Don't Stop\n"""|https://youtube.com/watch?v=iQI0zJd_cK4|1000.00|b'2:56\n'|100.0
b'Nightcore - Ievan Polkka (VSNS Remix)\n'|https://youtube.com/watch?v=QwdbFNGCkLw|40.00|b'3:51\n'|4.0
b''|https://youtube.com/watch?v=zS-VY7BbTls|1110.00|b''|111.0
"b""Nightcore - Don't Stop\n"""|https://youtube.com/watch?v=iQI0zJd_cK4|1111.00|b'2:56\n'|111.1
"b""Nightcore - Don't Stop\n"""|https://youtube.com/watch?v=iQI0zJd_cK4|100.00|b'2:56\n'|10.0
b'Nightcore - Ievan Polkka (VSNS Remix)\n'|https://youtube.com/watch?v=QwdbFNGCkLw|100.00|b'3:51\n'|10.0
```

**Comment by wipedlifepotato** [comment]
Если нужно прям в реальном времени, и сортировать по сумме доната там, то я думаю нужен CLI/GUI(что бы удалять старое из списка). GUI можно замутить на обычном GTK... Заморочка малех, но можно. 
CLI относительно проще, крч в любом случае заморочки и тесты, но можно, если надо.

**Comment by bitcoin5000** [comment]
Вместо русских символов белеберда в названии b'\xc2\xf1\xff \xef\xf0\xe0\xe2\xe4\xe0 \xef\xf0\xee \xc2\xe5\xeb\ также сохраняет \n' и b' зачемто в таблицу как она делится непонятно через ' или | ?
должны быть тока значение в таблице без b' и \n чтобы можно было сортировать по стоимости

**Comment by bitcoin5000** [comment]
и как одновремено редактировать в каком редакторе и чтобы работало? если открывать open office пишет acces denied когда еще хочит добавить когда открыт файл

**Comment by bitcoin5000** [comment]
также пустые строки добавляет через одну еще, редактор вроде нашел Rons Editor который не лочит файл когда открываешь

**Comment by wipedlifepotato** [comment]
Русские кодировку замути и wb изменить наверное ab на. Просто a .

чт, 14 мая 2020 г., 20:04 bitcoin5000 <notifications@github.com>:

**Comment by wipedlifepotato** [comment]
Делить через чо там изменить можно в коде delimeter

чт, 14 мая 2020 г., 20:19 potato livingstone <potatolivingstonei2p@gmail.com

**Comment by wipedlifepotato** [comment]
сделал
